version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "30001:80"
            - "30002:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/ssl:/etc/nginx/ssl:ro
            - ./site/51tywy:/usr/share/nginx/html:ro
        networks:
            - frontend
        depends_on:
            - php
    php:
        build: ./php/.
        volumes:
            - ./php/php.conf:/usr/local/etc/php/conf.d/php.conf:ro
            - ./site/51tywy:/usr/share/nginx/html
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
            - redis
    mysql:
        image: registry.aliyuncs.com/zhg_docker_ali_r/mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
            - ./site/mysqldata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: TYwy2016720
        networks:
            - backend
    redis:
        build: ./redis/.
        networks:
            - backend
    workerman:
        build: ./workerman/.
        ports:
           - "30083:8383"
           - "30032:3232"
        networks:
           - backend
        tty: true
    oneapm:
        build: ./oneapm/.
        volumes:
            -  /var/run/docker.sock:/var/run/docker.sock
            - /proc/:/host/proc/:ro
            - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro 
        networks:
            - backend
        environment:
            LICENSE_KEY: VAQLBVBUBAIb193HHloTCV8aWxfe71ddVR9UVQYHH124fAIHS1YCGgdTe365AA8eVlYaAQY=
networks:
    frontend:
    backend:
